### PR TITLE
Non-linear severity

### PR DESCRIPTION
**Pull request by ChrisWaller26**
I have updated the severity component to be non-linear and adjusted the stanvars to reflect this.

### CODE REVIEW

**Comment by ChrisWaller26** [comment]
The frequency model now works with any non-linear function as the model uses `mu_claimcount` directly. However, we need to come up with a way for the frequency deductible adjustment to calculate the mu parameter for the lognormal for each policy using the non-linear function form.

**Comment by Atan1988** [comment]
Awesome! Work has been a bit busy, and I haven't had a chance to test the latest commits.
________________________________

**Comment by ChrisWaller26** [comment]
No worries. This is meant to be an R&D project, so don't feel guilty if other things take priority.

**Comment by Atan1988** [comment]
It seems that the setup still runs into bias on the Poisson lambda estimation. I wonder whether the stanvar approach might be too challenging to pursue, given the current brms limitation of where we can insert the block.  Now that we can convert the stanfit object back into a brmsfit object,  should we continue down the path of #19?

**Comment by ChrisWaller26** [comment]
I didn't realise that you could convert Stan objects into BRMS ones, so that would definitely be a better approach. It would allow us to use the gsub / str_replace functions to overwrite the Stan code with out own changes but still get most of the benefits of BRMS generating all the design matrices, structure, etc. 

I believe there is a function to convert Stan function names to R ones, which we could implement later if we want to generalise the approach.

Are you able to merge this pull request or do you think it needs changes first?

**Review by Atan1988 — COMMENTED** [review]
I think the issue might still be stemming from the same linear shortcut we discussed earlier, but now on sigma only:
sigma_loss is defined as Intercept_sigma_loss + Xc_sigma_loss * b_sgima_loss

in our likelihood block we define sigma as Intercept_sigma_loss + X_claimcount_f1[, 2:K_sigma_loss] * b_sigma_loss

**Pull request merged**
