### PR TITLE
Added rating factors and limit censoring

### PR DESCRIPTION
**Pull request by ChrisWaller26**
The severity model now allows for truncation at the limit and the frequency model adjusts for rating factors.

However, there are the following caveats:

1. The method assumes frequency and severity have the same rating factors
2. The model gives reasonable results for severity but the frequency parameters are not looking right. I want to be able to return the ground up frequency lambda (i.e. 2 or 3) but the predictions seem a lot lower (~0.7, ~1) which I think is due to it giving me net lambda parameters. Is there an easy way to output the from ground up lambda?

### CODE REVIEW

**Comment by Atan1988** [comment]
Chris, 

    Because we use the poisson_log_lpmf function (default choice of brms and also specified in the stan code) rather than the poisson_lpmf function. The raw model output is log(lambda) rather than lambda.   

    Below is the sample output from the "frq vs sev model v2.R" code:
  Inference for Stan model: frq vs sev stancode v3.
4 chains, each with iter=2000; warmup=1000; thin=1; 
post-warmup draws per chain=1000, total post-warmup draws=4000.


                        mean se_mean   sd      2.5%       25%       50%       75%     97.5% n_eff Rhat
b_claimcount_f1[1]     -0.73    0.00 0.05     -0.82     -0.76     -0.73     -0.70     -0.63  2378    1
b_claimcount_f1[2]      0.38    0.00 0.06      0.27      0.34      0.38      0.42      0.50  2508    1
b_loss[1]               7.98    0.00 0.10      7.79      7.91      7.98      8.05      8.17  2033    1
b_loss[2]              -1.10    0.00 0.13     -1.35     -1.19     -1.10     -1.01     -0.84  2269    1
b_loss[3]               1.03    0.00 0.12      0.79      0.95      1.03      1.11      1.27  2345    1
sigma_loss              2.02    0.00 0.04      1.95      1.99      2.02      2.05      2.11  2953    1
lp__               -15168.20    0.04 1.73 -15172.51 -15169.13 -15167.86 -15166.93 -15165.81  1749    1

Samples were drawn using NUTS(diag_e) at Mon Jul 12 21:45:06 2021.
For each parameter, n_eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor on split chains (at 
convergence, Rhat=1).
    
We specify the ground - up lambda to be 0.5 and 0.5 + 0.2.  The intercept term exp(-0.73) is about 0.482; when the lambda factor is 1, the lambda would be exp(-0.73 + 0.38) =  0.70469.

**Comment by ChrisWaller26** [comment]
Hi Allen,

The lambda values I was referring to were after adjusting for the inverse-link function (i.e. exp) but this appears to be a problem with my code and not yours. I have not yet implemented your poisson_lognormal function you created. I will try this and see if this helps.

**Comment by Atan1988** [comment]
Don’t worry about the Poisson_lognormal function. I think it is illegal in the stan context.  I didn’t actually use it in the likelihood calculation. I wrote out the by-part in the model block.

It is a head-scratcher. I created standata and stancode from your setup, and I can’t think of anything that should prevent it from working.
I then passed the data into my setup, and it seems to be able to get a 0.69 lambda, which is close to 2.
I think it is definitely worth figuring out.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ChrisWaller26** [comment]
The method now works when rating factors are used for severity (including sigma) and frequency, provided the frequency component uses the same rating factors as the severity model and in the same order. The frequency model can have more rating factors than the severity model, provided they are after the other rating factors.

The reason this is the case is because I have used a stanvars function where mu and sigma are defined as:

`mu = Intercept_loss + X_claimcount_f1[, 2:K_loss] * b_loss
sigma = exp(Intercept_sigma_loss + X_claimcount_f1[, 2:K_loss] * b_sigma_loss)
`

So, provided the design matrix for frequency, X_claimcount, for column 2 to K_loss corresponds to the same factors for severity, then it should work.

Be aware that when BRMS creates the Stan code, the design matrix for claimcount has a first column of just 1s (i.e. an intercept) whereas the severity component explicitly defines the intercept, so does not do this. Hence, the need for the [, 2:K_loss] term.

**Comment by Atan1988** [comment]
I think this is a great solution, given that it would work entirely within the current brms framework without requiring any change.   
I ran the code within the master branch, and I got -0.35 for the claimcount_fi_Intercept and 1 for the claimamount_f1_regionUSC factor.  This would mean a 0.7 GU rate and then 1.9 for the USC region, which appear to be still underestimating the original ground up frequency of 2 and 3.   I am going to test a little bit more.

**Pull request merged**
