### PR TITLE
Non-linear functions work for Severity and Frequency

### PR DESCRIPTION
**Pull request by ChrisWaller26**
Apologies for the lateness in my response.

I have adapted the approach to use a template Stan model which is then edited using the str_glue function.

The model now produces the correct from ground up lambda and severity parameters.

The next step is to put this into a function and test it on a range of different structures.

### CODE REVIEW

**Comment by ChrisWaller26** [comment]
close #22

**Comment by ChrisWaller26** [comment]
close #13 
close #14

**Comment by Atan1988** [comment]
I will review, test and merge over this weekend! I am excited about the progress you have made, Chris!

**Comment by ChrisWaller26** [comment]
The function now converts linear models into non-linear ones automatically 
close #26

**Comment by ChrisWaller26** [comment]
I have tested the model with splines and it all appears to be working

close #15 
close #16

**Comment by Atan1988** [comment]
I have reviewed the main function, and also tested it. I think it will work very well. It is cool how the conditional likelihood is implemented by multiplying response type indicator freq[n].

**Comment by Atan1988** [comment]
One thing I missed in the original comment was that in the current Frequency Severity BRMS.R script, mu function doesn't really use the spline, which also resulted it to have super wide posterior interval and also very low ESS measures, while not really impacting the estimation of other parameters.  I guess this is also a demonstration of the power of the likelihood approach.

**Pull request merged**
